services:
  frontend:
    image: node:20-alpine
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - ./shared:/app/shared
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "8080:5173"
    environment:
      NODE_ENV: development
    networks:
      - app-network

  backend:
    image: node:20-alpine
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./shared:/app/shared
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:


networks:
  app-network:
    driver: bridge
