version: "3.9"

services:
  frontend:
    image: node:20-alpine
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - ./shared:/app/shared
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "8080:5173"
    environment:
      NODE_ENV: development
    networks:
      - app-network

  backend:
    image: node:20-alpine
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./shared:/app/shared
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
